name: Build and Test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      buildConfig: Release

    defaults:
      run:
        working-directory: app

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: >-
        dotnet build
        --no-restore
        -c ${{ env.buildConfig }}
    - name: Test
      run: >-
        dotnet test
        --no-build
        -c ${{ env.buildConfig }}
        --logger "trx;LogFileName=test-results.trx"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: app/LinkLite.Test/TestResults/test-results.trx
        reporter: dotnet-trx
